name: Build and Push Docker Image to Yandex Container Registry

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: vatsim-auth-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate GitHub release (if not exists)
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Yandex Container Registry
        run: echo "${{ secrets.YC_IAM_TOKEN }}" | docker login --username oauth --password-stdin cr.yandex

      - name: Build and Push Docker Image
        run: |
          docker build -t cr.yandex/${{ secrets.YC_REGISTRY_ID }}/$IMAGE_NAME:${{ github.ref_name }} .
          docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/$IMAGE_NAME:${{ github.ref_name }}

      - name: Display Success Message
        run: echo "🎉 Successfully pushed image with tag ${{ github.ref_name }}"